// Automaticaly generated by rust_swig
package net.korul.hbbft;

import android.support.annotation.NonNull;

public interface MyObserver {


    void onStateChanged(boolean a0, @NonNull String a1, @NonNull String a2);

}
